# Generated by Django 3.2.25 on 2025-02-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
